### PR TITLE
Fixed bug with synchronous multi component asyncConnect.

### PR DESCRIPTION
**Pull request by thomasdrakebjss**
Changed recursive promise resolution to instead use a loop and a final resolve return. This is related to #78

### CODE REVIEW

**Comment by AVVS** [comment]
Please do not change mapSeries - this is not where you should make changes. mapSeries works exactly how it should work.

You need to apply changes where components are flattened and then promises are iterated over in the mapSeries. When we have branching in the component we can resolve their statics asynchronously, but we need this to be resolved before getting onto nested statics

It should work like this:

```
Promise.mapSeries([
  [a, b] components A, B rendered in MainLayout resolve different statics -> Promise.map(a, b)
  c,  -- can use smth from a or b (assume its nested in (a)), so uses smth from promise (a) -> uses previous data from Promise['all' || 'map']([a, b])
  e,  -- uses previous data from [a, b] & c -- Promise(...)
  [f, g] -- uses previous data from -- Promise['all' || 'map'](...)
])
```

**Comment by thomasdrakebjss** [comment]
Ok I understand. So the aim for this given a routing structure as follows:

```
<Route component={Home}>
  <Route components={{ compA: CompA, compB: CompB }}>
    <IndexRoute components={{ compC: CompC, compD: CompD, compE: CompE }}/>
  </Route>
</Route>
```
Is to resolve the promises in the order:
Home then (CompA & CompB) then (CompC & CompD & CompE)?

**Comment by AVVS** [comment]
@thomasdrakebjss yes, you are exactly right

**Comment by thomasdrakebjss** [comment]
@AVVS I have undone the changes to mapSeries and implemented it using a multidimensional array. I added a new function as I couldn't figure a way to tie filterAndFlattenComponents and eachComponents the way it was working before. I have left the two functions in the code in case they are to be used again at some point. I can remove them if they are no longer needed, I was just suspicious with them being exported.

**Comment by AVVS** [comment]
tests do not cover some weird possible cases, so I'll play around with your code a little bit more and possibly simplify it. meanwhile it would be great if you can add test cases supporting layered layout

**Comment by thomasdrakebjss** [comment]
I have added a test case to support this change. It adds some extra bits to the router and makes sure the promises are resolved in the expected order.

**Pull request merged**
