### PR TITLE
Upgrade `react-redux` to 6, adhere to React Context API

### PR DESCRIPTION
**Pull request by ioanlucut**
In order to adhere to the new React context API.

Also, upgrades to the latest react-router-config beta version, adds the react-router-dom extra package as peer dependency, and upgrade all the other dependencies to their latest minor/major versions.

Also, drops the node 9 support, and focus on the LTE version of node (8, 10).

I got inspired from:
- https://github.com/reduxjs/react-redux/issues/1104
- https://github.com/supasate/connected-react-router/pull/191

### CODE REVIEW

**Comment by AVVS** [comment]
@ioanlucut thanks for the PR, this looks really good - only concern I have is that we reserve "store" property and it could potentially break the apps using it, what do you think?

**Comment by ioanlucut** [comment]
@AVVS thank you for having a look.
Do you mean this bit:
```
{({ store }) => <AsyncConnect store={store} {...otherProps} />}
``` ?

**Comment by AVVS** [comment]
yeah, this bit
if for some reason, store is passed as a prop to AsyncConnect in other props - it would lead to bugs

**Comment by ioanlucut** [comment]
@AVVS I can rename this prop to be e.g. `reduxStore` or anything.
Please let us know about the review progress. We are waiting very much for a new release. Thank you!

**Comment by ioanlucut** [comment]
@aleksxor I would appreciate a lot if you'd take some minutes to review this PR. Thanks!

**Comment by aleksxor** [comment]
the PR looks pretty good for me. though I have the same concern about prop naming. something like `reduxConnectStore` | `_reduxConnectStore` would make much smaller surface for possible collisions

**Comment by ioanlucut** [comment]
@aleksxor thanks for the feedback and the approval. Waiting for the merge and release! :)

**Comment by ioanlucut** [comment]
@AVVS When you find some time, please re-check! Thank you!

**Comment by ioanlucut** [comment]
Hi @AVVS ! I am sorry for stressing you out, but I'd appreciate a lot getting this PR merged.
We are literally blocked by this release in order to go with redux6.
Thank you for your time!

**Pull request merged**
